// Vendored VR API - the host contract. "Host" means the mod tree the vendored
// vr_* drop is embedded in: this tree, or a third-party mod that copied the
// drop. This header declares everything vr_cgame.c consumes from the host
// beyond stock 1.32 + the drop itself. If your tree satisfies this header,
// the drop compiles; there are no other hidden cgame dependencies.
//
// Do not edit this file. Per-tree choices live in vr_host_config.h, which the
// host owns.
#ifndef VR_HOST_H
#define VR_HOST_H

// No includes: this header is included only from the tail of cg_local.h,
// after q_shared.h/bg_public.h, the cg_t/cgs_t/centity_t definitions, and
// vr_host_config.h are already visible there (bg_public.h has no include
// guard, so re-including it here would be unsafe if this header were ever
// pulled in a second time).

// Defaults if the host config predates a macro (a bare drop assumes stock).
#ifndef VR_HOST_HAS_TV
#define VR_HOST_HAS_TV 0
#endif
#ifndef VR_HOST_HAS_WARMUP_EVENTS
#define VR_HOST_HAS_WARMUP_EVENTS 0
#endif

// ---- Tunables (host may predefine; defaults match this tree) --------------

#ifndef PLAYER_HEIGHT
#define PLAYER_HEIGHT 48
#endif

// worldscale multipliers for the dead / free spectator god-views
#ifndef SPECTATOR_WORLDSCALE_MULTIPLIER
#define SPECTATOR_WORLDSCALE_MULTIPLIER 10
#endif
#ifndef SPECTATOR2_WORLDSCALE_MULTIPLIER
#define SPECTATOR2_WORLDSCALE_MULTIPLIER 15
#endif

// ---- Functions the host must provide (absent from stock 1.32) -------------

// Draw one screen-space 2D overlay pass (damage border and friends) directly
// to the active render target. Called by the VR frame fork for passes that
// bypass the HUD buffer. A minimal host may draw nothing.
void CG_DrawScreen2D( void );

// Draw the reduced HUD used while the weapon zoom scope is up.
void CG_Draw2DMinimal( stereoFrame_t stereoFrame );

// Save (Push) and restore (Pop) the 2D anchor/placement transform around the
// VR HUD-buffer pass, so HUD elements lay out against the buffer's geometry
// instead of the screen's.
void CG_PushHUDAnchors( void );
void CG_PopHUDAnchors( void );

// The largest centered 4:3 box that fits the current framebuffer, in 640x480
// virtual units. On a plain 4:3 host this is simply 640x480.
void CG_GetViewable4x3Dimensions( float *outW, float *outH );

// The projection's optical center in 640x480 virtual coordinates - (320,240)
// unless the host renders asymmetric FOVs.
void CG_GetProjectionCenter( float *outX, float *outY );

// Add a laser/beam render entity from start to end (the drop's laser sight
// and aim-debug rays draw through this).
void CG_LaserSight( vec3_t start, vec3_t end, byte colour[4], float width );

#if VR_HOST_HAS_WARMUP_EVENTS
// Fire warmup/countdown announcer events during the HUD pass.
void CG_WarmupEvents( void );
#endif

// ---- Stock functions the host must export (static in stock 1.32) ---------
// Remove `static` at their stock definitions; CG_TrailItem also gains the
// offset/scale parameters shown here.

void CG_Draw2D( stereoFrame_t stereoFrame );
void CG_DrawCrosshair3D( void );
qboolean CG_WeaponSelectable( int i );
void CG_CalculateWeaponPosition( vec3_t origin, vec3_t angles );
void CG_OffsetFirstPersonView( void );
void CG_TrailItem( centity_t *cent, qhandle_t hModel, vec3_t offset, float scale );

// ---- Requirements this header cannot declare (structural) -----------------
//
// * bg_public.h: append STAT_VR_HEAD_PITCH and STAT_VR_HEAD_YAW_OFFSET at
//   your statIndex_t tail (VR_INTEGRATION.md Step 4).
// * Q_sscanf: this tree provides it in bg_lib; a stock tree maps it in
//   vr_host_config.h (#define Q_sscanf sscanf).
// * tr_types.h: RF_OVERBRIGHT, RF_WORLD_ORIENTED, RF_VIEW_ORIENTED, and the
//   tail-appended refEntity_t.invert are referenced by the drop; RT_LASERSIGHT and the
//   tail-appended refdef_t.isHUD are consumed by the host's own CG_LaserSight
//   and 2D passes. The two struct fields must remain LAST (see the guide's
//   Appendix E).
// * cg_t / cgs_t: no additions are required. All VR view/camera/HUD/selector
//   state the drop uses lives as module state inside vr_cgame.c; the host
//   reads what it needs through accessors (CG_VR_DrawingZoomedHUD,
//   CG_VR_ReticleShader) and resets drop state through call-outs
//   (CG_VR_DeathCamReset, CG_VR_PortraitReset). One field-shape change:
//   cgs.cursorX/cursorY become float (stock: int) -
//   CG_VR_ScoreboardCursor writes the cursor through float *. One existing
//   media entry changes scope: register cgs.media.friendShader
//   ("sprites/foe") in every gametype, not just GT_TEAM - the weapon
//   wheel's selection marker draws through it.
// * baseq3 UI (q3_ui): the uniform-scale uiStatic_t fields
//   scale/biasX/biasY/cursorScaleR/screenXmin..Ymax replace stock
//   xscale/yscale/bias, and uis.cursorx/uis.cursory become float (stock:
//   int) - UI_VR_CursorOverride writes the cursor through float * (see
//   Appendix E).
// * Team Arena UI: displayContextDef_t gains
//   void (*vrMenuMove)(void); wire it to the drop's UI_VR_OnMenuMove /
//   CG_VR_OnMenuMove. Its cursorx/cursory also become float (stock: int)
//   - UI_VR_CursorOverride writes the cursor through float *.

#endif // VR_HOST_H
